-- 1
use UNIVER
GO
CREATE VIEW [ПРЕПОДАВАТЕЛЬ]
	AS SELECT
		TEACHER.TEACHER_NAME,
		TEACHER.GENDER,
		TEACHER.PULPIT
	FROM TEACHER;

DROP VIEW [ПРЕПОДАВАТЕЛЬ]

-- 2
use UNIVER
GO
CREATE VIEW [КОЛИЧЕСТВО_КАФЕДР]
	AS SELECT
		FACULTY.FACULTY_NAME [ФАКУЛЬТЕТ],
		COUNT(PULPIT.FACULTY) [КОЛИЧЕСТВО]
	FROM FACULTY JOIN PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
	GROUP BY PULPIT.FACULTY, FACULTY.FACULTY_NAME;

DROP VIEW [КОЛИЧЕСТВО_КАФЕДР]

-- 3
use UNIVER
GO
CREATE VIEW [АУДИТОРИИ]
	AS SELECT
		AUDITORIUM.AUDITORIUM,
		AUDITORIUM.AUDITORIUM_TYPE
	FROM AUDITORIUM;

GO
INSERT АУДИТОРИИ VALUES('222-4', 'ЛК');

DROP VIEW [АУДИТОРИИ]

-- 4
use UNIVER
GO
CREATE VIEW [ЛЕКЦИОННЫЕ_АУДИТОРИИ]
	AS SELECT
		AUDITORIUM.AUDITORIUM,
		AUDITORIUM.AUDITORIUM_TYPE
	FROM AUDITORIUM
	WHERE AUDITORIUM.AUDITORIUM_TYPE LIKE 'ЛК%' WITH CHECK OPTION;

GO
INSERT ЛЕКЦИОННЫЕ_АУДИТОРИИ VALUES('417-4', 'ЛБ-Б');

GO
UPDATE ЛЕКЦИОННЫЕ_АУДИТОРИИ
SET AUDITORIUM_TYPE = 'ЛБ-Б'
WHERE AUDITORIUM = '222-4';

DROP VIEW [ЛЕКЦИОННЫЕ_АУДИТОРИИ]

-- 5
use UNIVER;
GO
CREATE VIEW [ДИСЦИПЛИНЫ]
	AS SELECT TOP(5) SUBJECT, SUBJECT_NAME, PULPIT
	FROM SUBJECT
	ORDER BY SUBJECT.SUBJECT_NAME;

DROP VIEW [ДИСЦИПЛИНЫ]

-- 6
use UNIVER;
GO
ALTER VIEW [КОЛИЧЕСТВО_КАФЕДР] WITH SCHEMABINDING
	AS SELECT
		FACULTY_NAME [ФАКУЛЬТЕТ],
		COUNT(PULPIT) [КОЛИЧЕСТВО]
	FROM dbo.FACULTY JOIN dbo.PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
	GROUP BY FACULTY_NAME, FACULTY.FACULTY_NAME;