use UNIVER
select FACULTY.FACULTY, PULPIT.PULPIT, PROFESSION.PROFESSION_NAME, SUBJECT.SUBJECT_NAME, STUDENT.NAME,
case
	when (PROGRESS.NOTE = 6) then 'רוסעü'
	when (PROGRESS.NOTE = 7) then 'סולü'
	when (PROGRESS.NOTE = 8) then 'גמסולü'
end [NOTE]
from STUDENT inner Join PROGRESS on STUDENT.IDSTUDENT = PROGRESS.IDSTUDENT 
inner join SUBJECT on PROGRESS.SUBJECT = SUBJECT.SUBJECT and (PROGRESS.NOTE between 6 and 8)
inner join GROUPS on STUDENT.IDGROUP = GROUPS.IDGROUP
inner join PULPIT on SUBJECT.PULPIT = PULPIT.PULPIT
inner join PROFESSION on PROFESSION.PROFESSION = GROUPS.PROFESSION
inner join FACULTY on GROUPS.FACULTY = FACULTY.FACULTY
order by FACULTY.FACULTY, PULPIT.PULPIT, PROFESSION.PROFESSION,-- STUDENT.NAME ASC,
(case
	when(PROGRESS.NOTE = 7) then 1
	when(PROGRESS.NOTE = 8) then 2
	when(PROGRESS.NOTE = 6) then 3
end);