use UNIVER

-- 1
SELECT PULPIT.PULPIT_NAME
FROM FACULTY, PULPIT
WHERE FACULTY.FACULTY = PULPIT.FACULTY and
	FACULTY.FACULTY in (
		SELECT PROFESSION.FACULTY
		FROM PROFESSION
		WHERE (
			PROFESSION.PROFESSION_NAME like '%технология%' or
			PROFESSION.PROFESSION_NAME like '%технологии%'
		)
	);

-- 2
SELECT PULPIT.PULPIT_NAME
FROM FACULTY  inner join PULPIT
ON FACULTY.FACULTY = PULPIT.FACULTY and
	FACULTY.FACULTY in (
		SELECT PROFESSION.FACULTY
		FROM PROFESSION
		WHERE (
			PROFESSION.PROFESSION_NAME like '%технология%' or
			PROFESSION.PROFESSION_NAME like '%технологии%'
		)
	);

-- 3
SELECT DISTINCT PULPIT.PULPIT_NAME
FROM FACULTY
inner join PULPIT ON FACULTY.FACULTY = PULPIT.FACULTY
inner join PROFESSION ON PROFESSION.FACULTY = FACULTY.FACULTY and
	(PROFESSION.PROFESSION_NAME like '%технология%' or
			PROFESSION.PROFESSION_NAME like '%технологии%');

-- 4
SELECT a.AUDITORIUM,
	a.AUDITORIUM_CAPACITY,
	a.AUDITORIUM_TYPE
FROM AUDITORIUM AS a
WHERE a.AUDITORIUM = (
		SELECT TOP(1) b.AUDITORIUM
		FROM AUDITORIUM AS b
		WHERE b.AUDITORIUM_TYPE = a.AUDITORIUM_TYPE
		ORDER BY b.AUDITORIUM_CAPACITY DESC
	)
ORDER BY a.AUDITORIUM_CAPACITY DESC;

-- 5
SELECT FACULTY.FACULTY_NAME
FROM FACULTY
WHERE not exists (
	SELECT * FROM PULPIT
	WHERE PULPIT.FACULTY = FACULTY.FACULTY
);

-- 6
SELECT TOP(1)
	(SELECT AVG(PROGRESS.NOTE) FROM PROGRESS
		WHERE PROGRESS.SUBJECT = 'ОАиП') [ОАиП],
	(SELECT AVG(PROGRESS.NOTE) FROM PROGRESS
		WHERE PROGRESS.SUBJECT = 'БД') [БД],
	(SELECT AVG(PROGRESS.NOTE) FROM PROGRESS
		WHERE PROGRESS.SUBJECT = 'СУБД') [СУБД]
FROM PROGRESS;

-- 7
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM.AUDITORIUM_CAPACITY
FROM AUDITORIUM
WHERE AUDITORIUM.AUDITORIUM_CAPACITY >= all (
	SELECT AUDITORIUM.AUDITORIUM_CAPACITY
	FROM AUDITORIUM
	WHERE AUDITORIUM.AUDITORIUM_TYPE = 'ЛБ-К')
		and AUDITORIUM.AUDITORIUM_TYPE = 'ЛК';

-- 8
SELECT AUDITORIUM.AUDITORIUM, AUDITORIUM.AUDITORIUM_CAPACITY
FROM AUDITORIUM
WHERE AUDITORIUM.AUDITORIUM_CAPACITY <=any (
	SELECT AUDITORIUM.AUDITORIUM_CAPACITY
	FROM AUDITORIUM
	WHERE AUDITORIUM.AUDITORIUM_TYPE = 'ЛК')
		and AUDITORIUM.AUDITORIUM_TYPE = 'ЛБ-К';